/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AddMovieRouteImport } from './routes/addMovie'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MovieEditRouteImport } from './routes/movie/edit'
import { Route as MovieMovieIdIndexRouteImport } from './routes/movie/$movieId/index'

const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AddMovieRoute = AddMovieRouteImport.update({
  id: '/addMovie',
  path: '/addMovie',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieEditRoute = MovieEditRouteImport.update({
  id: '/movie/edit',
  path: '/movie/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieMovieIdIndexRoute = MovieMovieIdIndexRouteImport.update({
  id: '/movie/$movieId/',
  path: '/movie/$movieId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addMovie': typeof AddMovieRoute
  '/favorites': typeof FavoritesRoute
  '/movie/edit': typeof MovieEditRoute
  '/movie/$movieId': typeof MovieMovieIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addMovie': typeof AddMovieRoute
  '/favorites': typeof FavoritesRoute
  '/movie/edit': typeof MovieEditRoute
  '/movie/$movieId': typeof MovieMovieIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addMovie': typeof AddMovieRoute
  '/favorites': typeof FavoritesRoute
  '/movie/edit': typeof MovieEditRoute
  '/movie/$movieId/': typeof MovieMovieIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addMovie'
    | '/favorites'
    | '/movie/edit'
    | '/movie/$movieId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/addMovie' | '/favorites' | '/movie/edit' | '/movie/$movieId'
  id:
    | '__root__'
    | '/'
    | '/addMovie'
    | '/favorites'
    | '/movie/edit'
    | '/movie/$movieId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddMovieRoute: typeof AddMovieRoute
  FavoritesRoute: typeof FavoritesRoute
  MovieEditRoute: typeof MovieEditRoute
  MovieMovieIdIndexRoute: typeof MovieMovieIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addMovie': {
      id: '/addMovie'
      path: '/addMovie'
      fullPath: '/addMovie'
      preLoaderRoute: typeof AddMovieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/edit': {
      id: '/movie/edit'
      path: '/movie/edit'
      fullPath: '/movie/edit'
      preLoaderRoute: typeof MovieEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$movieId/': {
      id: '/movie/$movieId/'
      path: '/movie/$movieId'
      fullPath: '/movie/$movieId'
      preLoaderRoute: typeof MovieMovieIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddMovieRoute: AddMovieRoute,
  FavoritesRoute: FavoritesRoute,
  MovieEditRoute: MovieEditRoute,
  MovieMovieIdIndexRoute: MovieMovieIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
