/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as CreateMovieRouteImport } from './routes/createMovie'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MovieMovieIdIndexRouteImport } from './routes/movie/$movieId/index'

const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateMovieRoute = CreateMovieRouteImport.update({
  id: '/createMovie',
  path: '/createMovie',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieMovieIdIndexRoute = MovieMovieIdIndexRouteImport.update({
  id: '/movie/$movieId/',
  path: '/movie/$movieId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/createMovie': typeof CreateMovieRoute
  '/favourites': typeof FavouritesRoute
  '/movie/$movieId/': typeof MovieMovieIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/createMovie': typeof CreateMovieRoute
  '/favourites': typeof FavouritesRoute
  '/movie/$movieId': typeof MovieMovieIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/createMovie': typeof CreateMovieRoute
  '/favourites': typeof FavouritesRoute
  '/movie/$movieId/': typeof MovieMovieIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/createMovie' | '/favourites' | '/movie/$movieId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/createMovie' | '/favourites' | '/movie/$movieId'
  id: '__root__' | '/' | '/createMovie' | '/favourites' | '/movie/$movieId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateMovieRoute: typeof CreateMovieRoute
  FavouritesRoute: typeof FavouritesRoute
  MovieMovieIdIndexRoute: typeof MovieMovieIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/createMovie': {
      id: '/createMovie'
      path: '/createMovie'
      fullPath: '/createMovie'
      preLoaderRoute: typeof CreateMovieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/$movieId/': {
      id: '/movie/$movieId/'
      path: '/movie/$movieId'
      fullPath: '/movie/$movieId/'
      preLoaderRoute: typeof MovieMovieIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateMovieRoute: CreateMovieRoute,
  FavouritesRoute: FavouritesRoute,
  MovieMovieIdIndexRoute: MovieMovieIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
