/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as AddMovieRouteImport } from './routes/addMovie'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MovieIndexRouteImport } from './routes/movie/index'

const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const AddMovieRoute = AddMovieRouteImport.update({
  id: '/addMovie',
  path: '/addMovie',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MovieIndexRoute = MovieIndexRouteImport.update({
  id: '/movie/',
  path: '/movie/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addMovie': typeof AddMovieRoute
  '/favourites': typeof FavouritesRoute
  '/movie/': typeof MovieIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addMovie': typeof AddMovieRoute
  '/favourites': typeof FavouritesRoute
  '/movie': typeof MovieIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addMovie': typeof AddMovieRoute
  '/favourites': typeof FavouritesRoute
  '/movie/': typeof MovieIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/addMovie' | '/favourites' | '/movie/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/addMovie' | '/favourites' | '/movie'
  id: '__root__' | '/' | '/addMovie' | '/favourites' | '/movie/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddMovieRoute: typeof AddMovieRoute
  FavouritesRoute: typeof FavouritesRoute
  MovieIndexRoute: typeof MovieIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addMovie': {
      id: '/addMovie'
      path: '/addMovie'
      fullPath: '/addMovie'
      preLoaderRoute: typeof AddMovieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movie/': {
      id: '/movie/'
      path: '/movie'
      fullPath: '/movie/'
      preLoaderRoute: typeof MovieIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddMovieRoute: AddMovieRoute,
  FavouritesRoute: FavouritesRoute,
  MovieIndexRoute: MovieIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
